### ISSUE TITLE
Filter by a column

### ISSUE THREAD

**Issue by ctorreiro** [OntimizeWeb/ontimize-web-ngx#236] opened 2018-12-03 11:52 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
In a table I have a column of the boolean type and the filter by column does not work.

The table is the following:

```
<o-table entity="EMobPurchasesDeliveryNotes" attr="deliveries" keys="deliverynote_id" columns="deliverynote_id;document_date;deliverynote_code;total_tax_base;total_vat;in_store;invoiced;not_invoiceable"
  visible-columns="document_date;deliverynote_code;total_tax_base;total_vat;in_store;invoiced;not_invoiceable" refresh-button="no" insert-button="no" pageable="yes" query-rows="20" service-type="FilterBySupplier" query-method="queryFiltered">
 
  <o-table-columns-filter columns="in_store;invoiced"></o-table-columns-filter>

  <!-- ... -->

  <o-table-column attr="in_store" title="{{'in_store' | oTranslate }}" type="boolean" true-value="check_circle" false-value="highlight_off" true-value-type="icon" false-value-type="icon" boolean-type="boolean"></o-table-column>
  <o-table-column attr="invoiced" title="{{'invoiced' | oTranslate }}" type="boolean" true-value="check_circle" false-value="highlight_off" true-value-type="icon" false-value-type="icon" boolean-type="number"></o-table-column>

</o-table>
```

When I select the option to filter by column and try to filter by the value true, the table remains the same. The same happens when I try to filter by the value false.

## Expected behavior

The "filter by a column" option should filter the table when the column is a type boolean.

## Minimal reproduction of the problem with instructions
![image](https://user-images.githubusercontent.com/26895503/49371943-5b120f80-f6f9-11e8-8f37-e30ab742b4b7.png)

![image](https://user-images.githubusercontent.com/26895503/49372006-885ebd80-f6f9-11e8-96f0-46642b09af53.png)

![image](https://user-images.githubusercontent.com/26895503/49372028-9c0a2400-f6f9-11e8-9cb5-35a32b135959.png)

## Environment

<pre><code>
Angular version: 3.1.2

Browser: 
- [x] Chrome (desktop) version 70.0.3538.110
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: v8.12.0
- Platform:  Windows

</code></pre>

**Comment by patricia-martinez-imatia** [comment] 2018-12-04 09:58
I close this issue because it is not a bug of Ontimize Web but of the rest service that does not filter well.

**Closed by patricia-martinez-imatia** 2018-12-04 09:58 UTC
