### ISSUE TITLE
o-grid registerQuickFilter() not working with o-search-input

### ISSUE THREAD

**Issue by jorge-diazs** [OntimizeWeb/ontimize-web-ngx#703] opened 2021-08-04 09:36 UTC
### What is the current behavior?
I'm trying to register some o-search-input from a mat-toolbar to work against my o-grid component data (using the grid's own toolbar is not a solution for my specific case), but it's not working. It shows the following message: "No column has been selected to perform the search", even though I'm specifying the same columns the grid declares as quick-filter-columns in my o-search-input columns attribute.

### Steps to reproduce
HTML:
<mat-toolbar>
      <o-search-input #search class="o-search-input" columns="EMPLOYEENAME;EMPLOYEESURNAME;EMPLOYEEADDRESS;EMPLOYEEEMAIL;OFFICEID"></o-search-input>
    </mat-toolbar>
    <o-grid #grid attr="employees" service="employees" entity="employee" 
columns="EMPLOYEEID;EMPLOYEETYPEID;EMPLOYEENAME;EMPLOYEESURNAME;EMPLOYEEADDRESS;EMPLOYEESTARTDATE;EMPLOYEEEMAIL;OFFICEID;EMPLOYEEPHOTO;EMPLOYEEPHONE;NAME"
      quick-filter-columns="EMPLOYEENAME;EMPLOYEESURNAME;EMPLOYEEADDRESS;EMPLOYEEEMAIL;OFFICEID"
      keys="EMPLOYEEID" sort-columns="EMPLOYEESURNAME" pageable="yes" query-rows="16" fixed-header="yes"
      refresh-button="no" gutter-size="18px" detail-mode="none" controls="no" (onDataLoaded)="onDataLoaded()">

TS:
@ViewChild('grid', { static: true })
grid: OGridComponent;
@ViewChild('search', { static: true })
searchInput: OSearchInputComponent;

ngAfterViewInit(): void {
    this.grid.registerQuickFilter(this.searchInput);
  }

### Affected versions:
- `ontimize-web-ngx`: 8.3.1

**Comment by gonzalo-martinez-imt** [comment] 2021-09-02 07:56
Unable to reproduce it in versions 8.3.1, 8.4.1 and current 8.5.0 development branch, closing by now

**Closed by gonzalo-martinez-imt** 2021-09-02 07:56 UTC
Labels: bug
